name = "MLDatasets"
uuid = "eb30cadb-4394-5ae3-aed4-317e484a6458"
version = "0.5.14"

[deps]
BinDeps = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
GZip = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Pickle = "fbb45041-c46e-462f-888f-7c521cafbc2c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
BinDeps = "1"
ColorTypes = "0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.10, 0.11"
DataDeps = "0.3, 0.4, 0.5, 0.6, 0.7"
FixedPointNumbers = "0.3, 0.4, 0.5, 0.6, 0.7, 0.8"
GZip = "0.5"
ImageCore = "0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8"
JSON3 = "1"
MAT = "0.7, 0.8, 0.9, 0.10"
Pickle = "0.2, 0.3"
Requires = "1"
julia = "1.3"

[extras]
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ImageCore"]
