name = "MLDatasets"
uuid = "eb30cadb-4394-5ae3-aed4-317e484a6458"
version = "0.4.0"

[deps]
BinDeps = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
GZip = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
ColorTypes = "≥ 0.4.0"
DataDeps = "≥ 0.3.0"
FixedPointNumbers = "≥ 0.3.0"
ImageCore = "≥ 0.1.2"
julia = "≥ 1.0.0"

[extras]
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "MAT", "ImageCore"]
